spring.application.name=JPA-allopen-demo

# H2 Console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log SQL parameters
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
